---
title: 'Exercise 1_2_2: Manipulate Vector Data'
author: 'Stefan Jünger & Anne-Kathrin Stroppe'
date: 'Introduction to Geospatial Techniques for Social Scientists in R'
editor_options: 
  chunk_output_type: console
---

```{r knitr_init, echo=FALSE, cache=FALSE, include=FALSE}
# custom boxes
knitr::opts_template$set(
  clues = list(box.title = "Clues",
               box.body = list(fill = "#fff9dc", colour = "black"),
               box.header = list(fill = "#ffec8b", colour = "black"),
               box.icon = "fa-search",
               box.collapse = TRUE)
)
```

```{r klippy, echo=FALSE, include=TRUE}
klippy::klippy()
```

```{block, box.title = "1", box.body = list(fill = "white"), box.icon = "fa-star"}
Import the ESRI shapefile of German districts and the district attribute table.
Join the two data frames, transform the CRS to `EPSG:3035`, and check your changes. 
```

```{block, opts.label = "clues"}
You need to rename one of the id variables or adjust your join accordingly (`AGS = district_id`).
```


```{r first-exercise, solution = TRUE}
# load libraries
library(sf)
library(dplyr)

# Import data
german_districts <- 
  sf::read_sf("./data/VG250_KRS.shp") %>% 
  dplyr::mutate(district_id = as.numeric(AGS)) %>% 
  sf::st_transform(3035) %>% 
  dplyr::select(district_id,GEN)

attributes_districts <- readr::read_delim("./data/attributes_districts.csv",
                                          delim = ";") 

# Join data and transform
german_districts_enhanced <- 
  german_districts %>% 
  dplyr::left_join(attributes_districts, by = "district_id") 

# Check
sf::st_crs(german_districts_enhanced)

head(german_districts_enhanced, 2)
```

```{block, box.title = "2", box.body = list(fill = "white"), box.icon = "fa-star"}
We want a first descriptive visual of the distribution of charging stations in Cologne (or any other district of your choice) and the surrounding districts. 
Filter the district of Cologne (`district_id == "05315"`) and find the surrounding districts.
Calculate the number of chargers per district (`charger_count`) and the number of chargers per 1,000 inhabitants in each district (`charger_dens`). 
Plot the two columns for Cologne and its surrounding districts.
```

```{block, opts.label = "clues"}
You can use the dplyr function `sf::bind_rows()` to combine the two spatial objects, "Cologne" and "Cologne Surroundings".
```

```{r second-exercise, solution = TRUE}

# filter Cologne
cologne <-
  german_districts %>% 
  dplyr::filter(district_id == 5315)

# filter surrounding districts, append with Cologne data and select the charger column
cologne_sur <-
  german_districts %>%
  dplyr::filter(lengths(sf::st_touches(., cologne)) > 0) %>% 
  dplyr::bind_rows(cologne) 


# one pipe to rule them all
cologne_sur_enhanced  <-
  readr::read_delim("./data/charging_points_ger.csv", 
                                  delim =";") %>% 
   filter(!is.na(longitude) & !is.na(latitude)) %>% 
  sf::st_as_sf(
    .,    
    coords = c("longitude", "latitude"),
    crs = 4326
  ) %>% 
  sf::st_transform(. , crs = 3035) %>% 
  sf::st_join(., cologne_sur, join = sf::st_within) %>% 
  dplyr::group_by(district_id) %>%
  dplyr::summarise(charger_count = n()) %>% 
  sf::st_drop_geometry() %>% 
  left_join(cologne_sur, ., by = "district_id") %>% 
  left_join(., attributes_districts %>% dplyr::select(district_id, population), by = "district_id") %>% 
  dplyr::mutate(charger_dens = (charger_count*1000) / population)

# plot  
cologne_sur_enhanced %>% 
  dplyr::select(charger_count, charger_dens) %>% 
  plot(.)

```

```{block, box.title = "3", box.body = list(fill = "white"), box.icon = "fa-star"}
Save your data set of Cologne and its surrounding districts as an ESRI Shapefile. 
```

```{r third-exercise, solution = TRUE, eval = FALSE}
# Export as shapefile
sf::st_write(
  cologne_sur_enhanced, 
  dsn = "./data/participant_materials/cologne_charger_epsg3035.shp", 
  delete_layer = TRUE
)
```
