---
title: 'Exercise 1_4_1: Basic Raster Operations'
author: 'Stefan Jünger & Anne-Kathrin Stroppe'
date: 'Introduction to Geospatial Techniques for Social Scientists in R'
---

```{r knitr_init, echo=FALSE, cache=FALSE, include=FALSE}
# custom boxes
knitr::opts_template$set(
  clues = list(box.title = "Clues",
               box.body = list(fill = "#fff9dc", colour = "black"),
               box.header = list(fill = "#ffec8b", colour = "black"),
               box.icon = "fa-search",
               box.collapse = TRUE)
)
```

```{r klippy, echo=FALSE, include=TRUE}
klippy::klippy()
```

```{block, box.title = "1", box.body = list(fill = "white"), box.icon = "fa-star"}
Create a matrix with 8 rows and 8 columns filled with random numbers between 1 and 1000.
```

```{block, opts.label = "clues"}
You can create the numbers using the `sample()` function.
```

```{r first, solution = TRUE}
library(dplyr)

fancy_matrix <-
  sample(1:1000, 8*8, replace = TRUE) |> 
  matrix(nrow = 8, ncol = 8)

fancy_matrix
```


```{block, box.title = "2", box.body = list(fill = "white"), box.icon = "fa-star"}
Now, use this matrix to create a raster layer and plot it.
```

```{block, opts.label = "clues"}
The `terra::rast()` function can be fed with matrices to create a raster layer.
```

```{r second, solution = TRUE}
library(terra)

fancy_raster_layer <- terra::rast(fancy_matrix)

terra::plot(fancy_raster_layer)
```

The `terra::rast()` function can not only be used to create raster data on the fly, which is also quite boring. Instead, we can use it to import already prepared data.

```{block, box.title = "3", box.body = list(fill = "white"), box.icon = "fa-star"}
Import one of the raster `.tiff`  files in the `./data` folder of the workshop directory.
```

```{block, opts.label = "clues"}
Make sure your file paths are set correctly. You can check them with `getwd()`. Setting is done with `setwd()`.
```

```{r third, solution = TRUE}
immigrants_cologne <- terra::rast("./data/immigrants_cologne.tif")
```


```{block, box.title = "4", box.body = list(fill = "white"), box.icon = "fa-star"}
Import the data on immigrants and inhabitants. Create a new layer showing the proportion of immigrants in each grid cell between 0 and 1. Next, apply z-standardization and dichotomize the data to get information about which grid cells deviate from the overall mean. Plot both "versions" of the data to see how they compare.
```

```{block, opts.label = "clues"}
You can handle raster layers as any simple data table using `+`, `-`, or `/` operators. Z-standardization can be applied using the `terra::scale()` function.
```

```{r fourth, solution = TRUE}
# load all layers
immigrants_cologne <-
  terra::rast("./data/immigrants_cologne.tif")

inhabitants_cologne <-
  terra::rast("./data/inhabitants_cologne.tif")

# create proportation layer
immigrants_proportion <- immigrants_cologne / inhabitants_cologne

# scale data
immigrants_proportion_scaled <- terra::scale(immigrants_proportation)

immigrants_proportion_scaled[immigrants_proportion_scaled < 0] <- 0
immigrants_proportion_scaled[immigrants_proportion_scaled > 0] <- 1

library(tmap)

tm_shape(immigrants_proportion) +
  tm_raster(palette = "-viridis")

tm_shape(immigrants_proportion_scaled) +
  tm_raster(palette = "-viridis")
```
