---
title: 'Exercise 2_1_2: Wrangling the German Census'
author: 'Stefan Jünger & Anne-Kathrin Stroppe'
date: 'Introduction to Geospatial Techniques for Social Scientists in R'
editor_options: 
  chunk_output_type: console
---

```{r knitr_init, echo=FALSE, cache=FALSE, include=FALSE}
# custom boxes
knitr::opts_template$set(
  clues = list(box.title = "Clues",
               box.body = list(fill = "#fff9dc", colour = "black"),
               box.header = list(fill = "#ffec8b", colour = "black"),
               box.icon = "fa-search",
               box.collapse = TRUE)
)

library(terra)
```

```{r klippy, echo=FALSE, include=TRUE}
klippy::klippy()
```


```{block, box.title = "1", box.body = list(fill = "white"), box.icon = "fa-star"}
Download the 1 km² attribute for the German Census 2011 immigrant rate, which has the German name `Auslaender_A`. Then, download the data for the vacancy rate (German name: `Leerstandsquote`) using the same raster resolution. Make sure to properly define missing values.
```

```{block, opts.label = "clues"}
The function for downloading is `z11::z11_get_1km_attribute()`, and the one for listing all attributes of this size is `z11::z11_list_1km_attributes()`. There, you can also see both of the layer names.
```

```{r first, solution = TRUE}
immigrant_rate_1km <- z11::z11_get_1km_attribute(Auslaender_A)

immigrant_rate_1km[immigrant_rate_1km <= -1] <- NA

vacany_rate_1km <- z11::z11_get_1km_attribute(Leerstandsquote)

vacany_rate_1km[vacany_rate_1km <= -1] <- NA

immigrant_rate_1km
vacany_rate_1km
```


```{block, box.title = "2", box.body = list(fill = "white"), box.icon = "fa-star"}
Crop both datasets to the extent of Berlin (or any other big German city if you want to).
```

```{block, opts.label = "clues"}
You can use the `osmdata:getbb()` function and the argument `format_out = "sf_polygon"` to receive a proper polygon for this purpose. Make sure only to extract the `multipolygon` and convert it to `EPSG:3035`.
```

```{r second, solution = TRUE}
berlin <- osmdata::getbb("Berlin", format_out = "sf_polygon")

berlin <- 
  berlin$multipolygon |>  
  sf::st_transform(3035)

immigrant_rate_1km_berlin <- terra::crop(immigrant_rate_1km, berlin)

vacancy_rate_1km_berlin <- terra::crop(vacany_rate_1km, berlin)
```


```{block, box.title = "3", box.body = list(fill = "white"), box.icon = "fa-star"}
That's an open exercise: How would you try to conduct a basic correlational analysis of both raster data attributes?
```

```{block, opts.label = "clues"}
You can coerce the whole raster data into a matrix using `terra::as.matrix(x)`
```

```{r third, solution = TRUE}
immigrant_rate_1km_berlin_z <- terra::scale(immigrant_rate_1km_berlin)

vacancy_rate_1km_berlin_z <- terra::scale(vacancy_rate_1km_berlin)

cor.test(
  terra::as.matrix(immigrant_rate_1km_berlin_z), 
  terra::as.matrix(vacancy_rate_1km_berlin_z),
  na.rm = TRUE
) 

pseudo_heatmap <- immigrant_rate_1km_berlin_z * vacancy_rate_1km_berlin_z

library(tmap)

tmap_arrange(
  tm_shape(immigrant_rate_1km_berlin_z) +
    tm_raster(palette = "-viridis", title = "") +
    tm_layout(title = "Immigrants"),
  tm_shape(vacancy_rate_1km_berlin_z) +
    tm_raster(palette = "-viridis", title = "") +
    tm_layout(title = "Vacancies"),
  tm_shape(pseudo_heatmap) +
    tm_raster(palette = "-viridis", title = "") +
    tm_layout(title = "Immigrants X Vacancies")
)
```