---
title: 'Exercise 2_1_1: Working with OSM Data'
author: 'Stefan Jünger & Anne-Kathrin Stroppe'
date: 'Introduction to Geospatial Techniques for Social Scientists in R'
---

```{r knitr_init, echo=FALSE, cache=FALSE, include=FALSE}
# custom boxes
knitr::opts_template$set(
  clues = list(box.title = "Clues",
               box.body = list(fill = "#fff9dc", colour = "black"),
               box.header = list(fill = "#ffec8b", colour = "black"),
               box.icon = "fa-search",
               box.collapse = TRUE)
)
```

```{r klippy, echo=FALSE, include=TRUE}
klippy::klippy()
```

```{block, box.title = "1", box.body = list(fill = "white"), box.icon = "fa-star"}
Pick a city of the world to your liking and retrieve its bounding box. Then plot it: What do you see?
```

```{block, opts.label = "clues"}
The function you may search for is part of the `data` package. Have a look at the slides.
```

```{r first, solution = TRUE}
boothbay <- osmdata::getbb("Boothbay")

plot(boothbay)

# We see two points, which build the extremes of the bounding box.
```


```{block, box.title = "2", box.body = list(fill = "white"), box.icon = "fa-star"}
Please choose a couple of building types you are interested in and set them as key and value pairs. You can find a list of building types in the [Overpass API documentation](https://wiki.openstreetmap.org/wiki/Key:building). But don't forget to set the timeout query parameters using the `osmdata::opq()` function first.
```

```{block, opts.label = "clues"}
First, specify the bounding box like before; second, the query parameters; and third, the key and value pairs. Try using a pipe workflow, as it makes it easier.
```

```{r second, solution = TRUE}
boothbay <-
  osmdata::getbb("Boothbay") |>  
  osmdata::opq(timeout = 25*100) |> 
  osmdata::add_osm_feature(
    key = "building", 
    value = c("house", "residential", "apartments", "detached", "bungalow")
  )
```

```{block, box.title = "3", box.body = list(fill = "white"), box.icon = "fa-star"}
Download the data using the `osmadata::osmdata_sf()` function and extract only the polygons. 
```

```{block, opts.label = "clues"}
The downloaded data is a list. The polygons are a named list element that you can extract with its name `osm_polygons`, just like a variable in a data table.
```

```{r third, solution = TRUE}
boothbay <-
  osmdata::getbb("Boothbay") |>  
  osmdata::opq(timeout = 25*100) |> 
  osmdata::add_osm_feature(
    key = "building", 
  ) |> 
  osmdata::osmdata_sf()

boothbay <- boothbay$osm_polygons
```


```{block, box.title = "4", box.body = list(fill = "white"), box.icon = "fa-star"}
Take some time to browse through the data. Depending on your chosen building type, you may find some interesting information. You can also plot the data you have just downloaded.
```

```{block, opts.label = "clues"}
You may consider converting the data into a tibble using `tibble::as_tibble()` and maybe a `sf::st_as_sf()` afterward for a nicer browsing experience.
```

```{r fourth, solution = TRUE}
library(tmap)

boothbay <-
  boothbay |> 
  tibble::as_tibble() |> 
  sf::st_as_sf()

boothbay

tmap_mode(("view"))

tm_shape(boothbay) +
  tm_polygons()
```


